<a href="https://colab.research.google.com/github/GioKhoma/Python_Data_Analytics/blob/main/Lecture3_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

scalar = np.array(42)
print(scalar)
print(scalar.ndim)

42
0


In [4]:
vector = np.array([1, 2, 3, 4, 5])
print(vector)
print(vector.ndim)

[1 2 3 4 5]
1


In [6]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(matrix)
print(matrix.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


In [8]:
arr = np.array([1, 2, 3, 4, 5])
# მონაცემთა ტიპის შემოწმება
arr.dtype
# განზომილების შემოწმება
arr.ndim
# ზომის შემოწმება
arr.size
# ფორმის შემოწმება
arr.shape

(5,)

In [15]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print("მასივი\n", arr)

# მონაცემთა ტიპის შემოწმება
print("\nმონაცემთა ტიპი:", arr.dtype)

# განზომილების შემოწმება
print("\nგანზომილება:", arr.ndim)

# ზომის შემოწმება
print("\nზომის შემოწმება:", arr.size)

# ფორმის შემოწმება
print("\nფორმა:", arr.shape)

მასივი
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

მონაცემთა ტიპი: int64

განზომილება: 2

ზომის შემოწმება: 10

ფორმა: (2, 5)


In [17]:
import numpy as np
print("ყველა ელემენტი == 0")
print(np.zeros((5, 5)))

print("\nყველა ელემენტი == 1")
print(np.ones((5, 5)))

print("\n5x5 ერთეულოვანი მატრიცა (identity matrix)")
print(np.identity(5))

print("\nმიმდევრობით")
print(np.arange(7, 23))

print("\nმიმდევრობით ნაზრდით")
print(np.arange(7, 23,3))

print("\nმიმდევრობით ათწილადი ნაზრდით")
print(np.arange(7, 15, 0.7))

print("\nფორმის შეცვლა reshape-ით")
print(np.arange(7, 15, 0.7).reshape(3, 4))


ყველა ელემენტი == 0
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

ყველა ელემენტი == 1
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

5x5 ერთეულოვანი მატრიცა (identity matrix)
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

მიმდევრობით
[ 7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]

მიმდევრობით ნაზრდით
[ 7 10 13 16 19 22]

მიმდევრობით ათწილადი ნაზრდით
[ 7.   7.7  8.4  9.1  9.8 10.5 11.2 11.9 12.6 13.3 14.  14.7]

ფორმის შეცვლა reshape-ით
[[ 7.   7.7  8.4  9.1]
 [ 9.8 10.5 11.2 11.9]
 [12.6 13.3 14.  14.7]]


In [20]:
# ვექტორის შექმნა
a = np.arange(10, 16)
print("ვექტორი:", a)
print("\nანათალი 1-ელი ელემენტიდან მე-5-მდე (ჩაუთვლელად):\n", a[1:5])
print("\nანათალი 1-ელი ელემენტიდან მე-5-მდე (ჩაუთვლელად) 2 ბიჯიანი ნაპრალით:\n", a[1:5:2])

# მატრიცის შექმნა
A = np.arange(10, 19).reshape((3, 3))
print("\n",A)
print("\n მე-0 სტრიქონის ყველა ელემენტი:", A[0,:])
print("\n მე-0 სვეტის ყველა ელემენტი:", A[:,0])


ვექტორი: [10 11 12 13 14 15]

ანათალი 1-ელი ელემენტიდან მე-5-მდე (ჩაუთვლელად):
 [11 12 13 14]

ანათალი 1-ელი ელემენტიდან მე-5-მდე (ჩაუთვლელად) 2 ბიჯიანი ნაპრალით:
 [11 13]

 [[10 11 12]
 [13 14 15]
 [16 17 18]]

 მე-0 სტრიქონის ყველა ელემენტი: [10 11 12]

 მე-0 სვეტის ყველა ელემენტი: [10 13 16]


In [22]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[4, 3], [2, 1]])

print(a > b)  # ელემენტობრივი შედარება
print(np.logical_and(a > 0, b > 0))  # ლოგიკური AND ოპერაცია
print(np.logical_or(a > 0, b > 0))  # ლოგიკური OR ოპერაცია

[[False False]
 [ True  True]]
[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]


In [25]:
import numpy as np
from numpy.linalg import inv, qr
a = np.array([[1, 2], [3, 4]])
b = np.array([[4, 3], [2, 1]])
# print(a)
print(a + b)  # მატრიცების შეკრება
print(a - b)  # მატრიცების გამოკლება
print(a * b)  # მატრიცების ელემენტობრივი გამრავლება
print(a.dot(b))  # მატრიცების გამრავლება
print(a / b)  # მატრიცების ელემენტობრივი გაყოფა
print(a * 2) # მატრიცის გამრავლება სკალარზე
print(a.T) # მატრიცის ტრანსპონირება
print(np.diag(a)) # მატრიცის დიაგონალური ელემენტების ამოღება
print(np.diag([1, 2, 3, 4])) # დიაგონალური მატრიცის შექმნა
# კვადრატული მატრიცის საკუთრივი მნიშვნელობების და საკუთრივი ვექტორების გამოთვლა:
a = np.array([[1, 2], [3, 4]])
eigenvalues, eigenvectors = np.linalg.eig(a)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:", eigenvectors)
print(np.linalg.inv(a)) # მატრიცის შებრუნებული მატრიცის გამოთვლა
print(np.linalg.det(a)) # მატრიცის დეტერმინანტის გამოთვლა

[[5 5]
 [5 5]]
[[-3 -1]
 [ 1  3]]
[[4 6]
 [6 4]]
[[ 8  5]
 [20 13]]
[[0.25       0.66666667]
 [1.5        4.        ]]
[[2 4]
 [6 8]]
[[1 3]
 [2 4]]
[1 4]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors: [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004


In [27]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
print(np.sum(a))  # ელემენტების ჯამი
print(np.mean(a))  # ელემენტების საშუალო
print(np.median(a))  # ელემენტების მედიანა
print(np.min(a))  # ელემენტების მინიმუმი
print(np.max(a))  # ელემენტების მაქსიმუმი
print(np.std(a))  # ელემენტების სტანდარტული გადახრა
print(np.var(a))  # ელემენტების დისპერსია

10
2.5
2.5
1
4
1.118033988749895
1.25


In [29]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
# ინკრემენტი და დეკრემენტი
arr1 += 1
arr2 -= 2
print(arr1, arr2)

[2 3 4] [2 3 4]


In [31]:
arr = np.array([1, 2, 3])
sqrt_arr = np.sqrt(arr)
exp_arr = np.exp(arr)
print(sqrt_arr, exp_arr)

[1.         1.41421356 1.73205081] [ 2.71828183  7.3890561  20.08553692]


In [33]:
arr = np.array([1, 2, 3, 4, 5])
min_result = np.min(arr)
sum_result = np.sum(arr)
max_result = np.max(arr)
print(min_result, sum_result, max_result)

1 15 5


In [36]:
# savarjishoebi
import numpy as np

arr = np.arange(0, 9)
print(arr)

[0 1 2 3 4 5 6 7 8]


In [40]:
arr = np.arange(0, 9).reshape(3, 3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [43]:
arr = np.arange(10, 20)
for i in arr:
  if i % 2 != 0:
    print(i, 'odd')

11 odd
13 odd
15 odd
17 odd
19 odd


In [52]:
arr = np.random.rand(3, 4)
arr[arr > 0.5] = 0

print(arr)

[[0.32342713 0.28815269 0.12932651 0.        ]
 [0.         0.         0.         0.08172141]
 [0.49730504 0.3124005  0.21481753 0.08670785]]


In [55]:
a = np.random.randint(1, 11, size=(3, 3))
b = np.random.randint(1, 11, size=(3, 3))

print(a)
print(b)
print("შეკრება:\n", a + b)
print("გამოკლება:\n", a - b)
print("გამრავლება:\n", a * b)
print("გაყოფა:\n", a / b)

[[ 1 10  3]
 [ 1  9  8]
 [ 7 10  2]]
[[1 9 2]
 [8 1 2]
 [9 3 1]]
შეკრება:
 [[ 2 19  5]
 [ 9 10 10]
 [16 13  3]]
გამოკლება:
 [[ 0  1  1]
 [-7  8  6]
 [-2  7  1]]
გამრავლება:
 [[ 1 90  6]
 [ 8  9 16]
 [63 30  2]]
გაყოფა:
 [[1.         1.11111111 1.5       ]
 [0.125      9.         4.        ]
 [0.77777778 3.33333333 2.        ]]


In [67]:
arr = np.random.randint(1, 101, size=20)
print(arr)
mean = arr.mean()
median = np.median(arr)
variance = np.var(arr)
std_dev = np.std(arr)

print('საშუალო', mean)
print('sum', arr.sum())
print('median', median)
print('variance', variance)
print('standard deviation', std_dev)

[20 76 62 57 61 42 54 77 76 30 61 69 90 39 56 54 53 88 33 61]
საშუალო 57.95
sum 1159
median 59.0
variance 331.4475
standard deviation 18.205699656975558


In [71]:
arr = np.random.randint(1, 21, size=(5, 5))

sorted_rows = np.sort(arr, axis=0)
sorted_column = np.sort(arr, axis=1)

print("საწყისი მასივი:\n", arr)

print("დალაგებული სტრიქონების მიხედვით:\n", sorted_column)
print("დალაგებული სვეტების მიხედვით:\n", sorted_rows)

საწყისი მასივი:
 [[ 8 18 14 16  4]
 [ 3  5  5 13  3]
 [ 9  9 10 10  5]
 [15 13  1 18  9]
 [14  9 18 18  9]]
დალაგებული სტრიქონების მიხედვით:
 [[ 4  8 14 16 18]
 [ 3  3  5  5 13]
 [ 5  9  9 10 10]
 [ 1  9 13 15 18]
 [ 9  9 14 18 18]]
დალაგებული სვეტების მიხედვით:
 [[ 3  5  1 10  3]
 [ 8  9  5 13  4]
 [ 9  9 10 16  5]
 [14 13 14 18  9]
 [15 18 18 18  9]]


In [75]:
a = np.arange(0, 9).reshape(3, 3)
b = np.arange(9, 18).reshape(3, 3)

vertical_combined = np.vstack((a, b))
horizontal_combined = np.hstack((a, b))

print(a)
print(b)

print("ვერტიკალურად გაერთიანება:\n", vertical_combined)
print("ჰორიზონტალურად გაერთიანება:\n", horizontal_combined)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
ვერტიკალურად გაერთიანება:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
ჰორიზონტალურად გაერთიანება:
 [[ 0  1  2  9 10 11]
 [ 3  4  5 12 13 14]
 [ 6  7  8 15 16 17]]


In [80]:
a = np.random.randint(1, 11, size=(3, 4))
b = np.arange(1, 5)

result = a + b
print(a)
print(b)
print(result)

[[ 3  7  6  8]
 [ 6 10  6  2]
 [ 7  3  7  4]]
[1 2 3 4]
[[ 4  9  9 12]
 [ 7 12  9  6]
 [ 8  5 10  8]]


In [81]:
a# შექმენით ორი 3x3 მატრიცა შემთხვევითი მთელი რიცხვებით 1-დან 10-მდე
matrix1 = np.random.randint(1, 11, size=(3, 3))
matrix2 = np.random.randint(1, 11, size=(3, 3))

# გამოთვალეთ სკალარული ნამრავლი
dot_product = np.dot(matrix1, matrix2)

# გამოთვალეთ საკუთრივი მნიშვნელობები და ვექტორები პირველი მატრიცისთვის
eigenvalues, eigenvectors = np.linalg.eig(matrix1)


# შედეგების გამოქვეყნება
print("პირველი მატრიცა:\n", matrix1)
print("\nმეორე მატრიცა:\n", matrix2)
print("\nსკალარული ნამრავლი (მატრიცების დოტ პროდუქტი):\n", dot_product)
print("\nსაკუთრივი მნიშვნელობები პირველი მატრიცისთვის:\n", eigenvalues)
print("\nსაკუთრივი ვექტორები პირველი მატრიცისთვის:\n", eigenvectors)

პირველი მატრიცა:
 [[ 1  2  5]
 [ 3  2  2]
 [10  7  6]]

მეორე მატრიცა:
 [[ 1 10  3]
 [ 4  8  8]
 [ 4  2  1]]

სკალარული ნამრავლი (მატრიცების დოტ პროდუქტი):
 [[ 29  36  24]
 [ 19  50  27]
 [ 62 168  92]]

საკუთრივი მნიშვნელობები პირველი მატრიცისთვის:
 [12.9138015  -3.77002094 -0.14378056]

საკუთრივი ვექტორები პირველი მატრიცისთვის:
 [[-0.4108707  -0.74568018  0.45367146]
 [-0.27238168  0.16383764 -0.85836496]
 [-0.87005373  0.64584696  0.23956586]]
